// const type = 'time' | 'freeRoll' | 'rapid' | 'knockout' | 'bounty' | 'proBounty';

export const tourmanentDate = [
  {
    id: 12,
    isCanceled: false,
    isPin: true,
    tag: 'NL 2-7 Triple Draw',
    types: [],
    title: 'OFC Pineapple',
    date: '12:00 pm, 28 July',
    players: {
      current: 1000,
      max: 1000,
    },
    tourney: 1000000,
  },
  {
    id: 13,
    isCanceled: false,
    isPin: true,
    tag: 'NL Holdem',
    types: [],
    title: 'OFC Pineapple',
    date: '12:00 pm, 28 July',
    players: {
      current: 1,
      max: 6,
    },
    tourney: 100,
  },
  {
    id: 14,
    isCanceled: true,
    isPin: true,
    tag: 'NL OFC/pineapple prg',
    types: ['time', 'freeRoll'],
    title: 'Hourly Freeroll',
    date: '12:00 pm, 28 July',
    players: {
      current: 1,
      max: 10000,
    },
    tourney: 1000,
  },
  {
    id: 21,
    isCanceled: true,
    isPin: false,
    tag: 'PL Omaha h/l',
    types: [],
    title: 'Rapid Tournament',
    date: '12:00 pm, 28 July',
    players: {
      current: 0,
      max: 0,
    },
    tourney: 1000000,
  },
  {
    id: 34,
    isCanceled: true,
    isPin: false,
    tag: 'NL 2-7 Triple Draw',
    types: [],
    title: 'PL Omaha Knockout',
    date: '12:00 pm, 28 July',
    players: {
      current: 0,
      max: 100,
    },
    tourney: 146,
  },
  {
    id: 54,
    isCanceled: false,
    isPin: true,
    tag: 'NL 2-7 Triple Draw',
    types: ['knockout', 'bounty', 'proBounty'],
    title: 'PL Omaha Knockout',
    date: '12:00 pm, 28 July',
    players: {
      current: 0,
      max: 100,
    },
    tourney: 146,
  },
  {
    id: 56,
    isCanceled: false,
    isPin: true,
    tag: 'NL 2-7 Triple Draw',
    types: ['knockout', 'bounty', 'proBounty'],
    title: 'PL Omaha Knockout',
    date: '12:00 pm, 28 July',
    players: {
      current: 0,
      max: 100,
    },
    tourney: 146,
  },
];
